# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6535a243ec65653c9cb846648dd8af64473546e96356afeb8ff28fe5ca27a3389adcf8bffb9e82a8a2ed8143dbb25cd1a2f279011a49ac3b3f8089a0d16ca9e9

test:
  secret_key_base: bee96ffdf2248d96a37d00c44378c250362b8b42e1aa151aef266bd7342a3d511026a08de31a7e459a78541a71c2e33d102d882c74ef358e97605c1fe58ebbd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
